/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mysql.cj.xdevapi.Result;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {
    Connection c = getConnection();
    DefaultTableModel mode = new DefaultTableModel();
    HashMap param = new HashMap();
    SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
    Color panelclicked;
    Color paneldefault;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        panelclicked = new Color(102,102,225);
        paneldefault = new Color(0,0,0);
        jPanel3.setBackground(panelclicked);
        jPanel5.setBackground(paneldefault);
        jPanel6.setBackground(paneldefault);
        jPanel7.setBackground(paneldefault);
        jPanel8.setBackground(paneldefault);
        jPanel9.setBackground(paneldefault);
        ShowTime();
        ShowDate();
        tabelAbsen();
        tabelDataSiswa();
        tabelDataSekolah();
        tabselJadwalPsg();
        tabelNilaiSiswa();
        ButtonGroup bg = new ButtonGroup();
        ButtonGroup bg2 = new ButtonGroup();
        ButtonGroup bg3 = new ButtonGroup();
        
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg2.add(jRadioButton3);
        bg2.add(jRadioButton4);
        bg3.add(jRadioButton5);
        bg3.add(jRadioButton6);
        jRadioButton3.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton5.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        absen = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelabsen = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        dataSekolah = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelDataSekolah = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jadwaPsg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelJadwal = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dataSiswa = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDataSiswa = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nilaiSiswa = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selamat Datang, Admin");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\absen.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 60));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\data_siswa.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 60));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\data_sekolah.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 60));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\jadwal psg.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 260, 60));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\nilai siswa.png")); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 260, 60));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\keluar.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 260, 60));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\astra_icon_kecil.png")); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 881));

        center.setLayout(new java.awt.CardLayout());

        absen.setBackground(new java.awt.Color(204, 204, 204));
        absen.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 262, 30));

        tabelabsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabelabsen);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 392, 1050, 268));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setText("Halaman Absen");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel27.setText("Jam");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, 30));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setText("Jam :");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setText("Tanggal");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setText("Masukan nis :");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel31.setText("Hari ini :");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_absen.png")); // NOI18N
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cetak.png")); // NOI18N
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        absen.add(jPanel12);
        jPanel12.setBounds(0, 0, 1110, 880);

        center.add(absen, "card3");

        dataSekolah.setBackground(new java.awt.Color(255, 255, 255));
        dataSekolah.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel42.setText("Data Sekolah");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cetak.png")); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setText("Nama Sekolah :");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        tabelDataSekolah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelDataSekolah);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1020, 550));

        jTextField5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel10.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\close.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\minim.png")); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cari.png")); // NOI18N
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        dataSekolah.add(jPanel10);
        jPanel10.setBounds(0, 0, 1040, 700);

        center.add(dataSekolah, "card4");

        jadwaPsg.setBackground(new java.awt.Color(204, 204, 204));
        jadwaPsg.setForeground(new java.awt.Color(0, 0, 102));
        jadwaPsg.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel45.setText("Data Jadwal PKL dan PSG");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel46.setText("Nama Siswa:");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jTextField6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, 30));

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cari.png")); // NOI18N
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        tabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelJadwal);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1020, 550));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\close.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\minim.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jadwaPsg.add(jPanel4);
        jPanel4.setBounds(0, 0, 1260, 880);

        center.add(jadwaPsg, "card5");

        dataSiswa.setBackground(new java.awt.Color(153, 153, 153));
        dataSiswa.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelDataSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataSiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelDataSiswa);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1040, 280));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("Data Siswa");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Nama Siswa :");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel11.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("NIS Siswa :");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jTextField3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel11.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Tanggal Mulai :");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, 30));

        jTextField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel11.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel11.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 200, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Jenis  Kelamin :");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Tanggal Selsai :");
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, 30));

        jDateChooser2.setDateFormatString("dd-MM-yyyy");
        jDateChooser2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel11.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 200, 30));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Asal Sekolah :");
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("Laki-Laki");
        jPanel11.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 30));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setText("Perempuan");
        jPanel11.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Divisi :");
        jPanel11.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, 30));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton3.setText("PSG");
        jPanel11.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, 30));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton4.setText("PKL");
        jPanel11.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cetak.png")); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_simpan.png")); // NOI18N
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_ubah.png")); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_hapus.png")); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\close.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\minim.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        dataSiswa.add(jPanel11);
        jPanel11.setBounds(0, 0, 1170, 880);

        center.add(dataSiswa, "card2");

        nilaiSiswa.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel40.setText("Data Nilai Siswa");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("NIS Siswa :");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jTextField7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Nama Siswa :");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jTextField8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 30));

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setText("Asal Sekolah :");
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jTextField9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_simpan.png")); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_ubah.png")); // NOI18N
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cetak_surat.png")); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelNilai);

        jPanel13.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1040, 280));

        jLabel54.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel54.setText("Masukan Nilai :");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, 30));

        jTextField10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 200, 30));

        jTextField11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 200, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Tanggal Selsai :");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Tanggal Mulai :");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, 30));

        jTextField12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel13.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 200, 30));

        jLabel48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel48.setText("Divisi :");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton5.setText("PSG");
        jPanel13.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton6.setText("PKL");
        jPanel13.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 30));

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\SistemInformasi_PKL\\PKL_IMG\\btn_cetak.png")); // NOI18N
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        nilaiSiswa.add(jPanel13);
        jPanel13.setBounds(0, 0, 1220, 880);

        center.add(nilaiSiswa, "card6");

        jPanel1.add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1, 1220, 880));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public Connection getConnection(){
        Connection con;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pkl", "root", "");
            return con;
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }
void ShowDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        jLabel29.setText(s.format(d));
    }
    void ShowTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                
                jLabel27.setText(s.format(d));
               
            }
           
        }).start();
    }
    private void MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked
        if (evt.getSource()==jLabel1){
            absen.setVisible(true);
            dataSiswa.setVisible(false);
            dataSekolah.setVisible(false);
            jadwaPsg.setVisible(false);
            nilaiSiswa.setVisible(false);
           
            jPanel3.setBackground(panelclicked);
            jPanel5.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
        }
            else if (evt.getSource()==jLabel2){
            absen.setVisible(false);
            dataSiswa.setVisible(true);
            dataSekolah.setVisible(false);
            jadwaPsg.setVisible(false);
            nilaiSiswa.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(panelclicked);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
        }
        else if (evt.getSource()==jLabel3){
            absen.setVisible(false);
            dataSiswa.setVisible(false);
            dataSekolah.setVisible(true);
            jadwaPsg.setVisible(false);
            nilaiSiswa.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(panelclicked);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
        }
            else if (evt.getSource()==jLabel4){
            absen.setVisible(false);
            dataSiswa.setVisible(false);
            dataSekolah.setVisible(false);
            jadwaPsg.setVisible(true);
            nilaiSiswa.setVisible(false);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(panelclicked);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(paneldefault);
            
         } else if (evt.getSource()==jLabel15){
            absen.setVisible(false);
            dataSiswa.setVisible(false);
            dataSekolah.setVisible(false);
            jadwaPsg.setVisible(false);
            nilaiSiswa.setVisible(true);
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(panelclicked);
            jPanel9.setBackground(paneldefault);
         }
        else if (evt.getSource()==jLabel5){
            
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel8.setBackground(paneldefault);
            jPanel9.setBackground(panelclicked);
            try {
            int yn = JOptionPane.showConfirmDialog(null, "Keluar aplikasi ?", "Keluar", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                Login l = new Login();
                l.setVisible(true);
                this.dispose();
            } else {
                
            }
            
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
           
            jPanel3.setBackground(paneldefault);
            jPanel5.setBackground(paneldefault);
            jPanel6.setBackground(paneldefault);
            jPanel7.setBackground(paneldefault);
            jPanel8.setBackground(panelclicked);
            jPanel9.setBackground(paneldefault);
         }
    }//GEN-LAST:event_MouseClicked

    public boolean absenByNip(String nis){
        boolean nisFound = false;
        try {
            PreparedStatement ps = c.prepareStatement("select * from datasiswa where Nis_Siswa=?");
            ps.setString(1, nis);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                nisFound = true;
            }
        } catch(Exception e) {
         
        }
        return nisFound;
    }
    public static void AddRowToTabelAbsen(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)tabelabsen.getModel();
        model.addRow(dataRow);
    }
    public static void AddRowToTabelDataSiswa(Object[] dataRow)
    {
        DefaultTableModel model = (DefaultTableModel)tabelDataSiswa.getModel();
        model.addRow(dataRow);
    }    public boolean checkDuplicate (String duplicate){
    boolean checkuser = false;
    
    try{
        PreparedStatement ps = c.prepareStatement("select * from datasiswa where nip =?");
        ps.setString(1, duplicate);
        ResultSet rs = ps.executeQuery();
        if (rs.next()){
            checkuser = true;
        }
        
    } catch (Exception e){
        
    } return checkuser;
}
    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
       String gender = "Perempuan";
       String divisi = "PSG";
       if(jRadioButton1.isSelected()){
           gender = "Laki-Laki";
       } else if(absenByNip(jTextField3.getText())){
           JOptionPane.showMessageDialog(null, "NIS sudah digunakan", "Warning", 2);
       } else if (jRadioButton4.isSelected()) {
           divisi = "PKL";
        }
       
        try{
           
           PreparedStatement ps = c.prepareStatement("insert into datasiswa values (?,?,?,?,?,?,?)");
           ps.setString(1, jTextField3.getText());
           ps.setString(2, jTextField2.getText());
           ps.setString(3, jTextField4.getText());
           ps.setString(4, gender);
           ps.setString(5, date.format(jDateChooser1.getDate()));
           ps.setString(6, date.format(jDateChooser2.getDate()));
           ps.setString(7, divisi);
          
          
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
           AddRowToTabelDataSiswa(new Object[]{
               jTextField3.getText(),
               jTextField2.getText(),
               jTextField4.getText(),
               gender,
               date.format(jDateChooser1.getDate()),
               date.format(jDateChooser2.getDate()),
               divisi
           });
            reset();
       } catch(Exception e){
           System.out.println("Gagal tambahkan data");
           JOptionPane.showMessageDialog(null,e);
       
       }
    
    }//GEN-LAST:event_jLabel37MouseClicked
   private void reset(){
    jTextField3.setText("");
    jTextField2.setText("");
    jTextField4.setText(""); 
    jDateChooser1.setCalendar(null);
    jDateChooser2.setCalendar(null);
}
    
    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
       String gender = "Perempuan";
       String divisi = "PSG";
       if(jRadioButton1.isSelected()){
           gender = "Laki-Laki";
       } else if (jRadioButton4.isSelected()) {
           divisi = "PKL";
        }
        try{
           PreparedStatement ps = c.prepareStatement("UPDATE datasiswa SET Nama_Siswa=?,Asal_Sekolah=?,Jenis_Kelamin=?,Tanggal_Masuk=?,Tanggal_Selesai=?,Divisi=? WHERE Nis_Siswa=?");
           ps.setString(7, jTextField3.getText());
           ps.setString(1, jTextField2.getText());
           ps.setString(2, jTextField4.getText());
           ps.setString(3, gender);
           ps.setString(4, date.format(jDateChooser1.getDate()));
           ps.setString(5, date.format(jDateChooser2.getDate()));
           ps.setString(6, divisi);
      
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil diubah");
           tabelDataSiswa();
            reset();
       
       } catch(Exception e){
           System.out.println("Gagal ubah data");
           JOptionPane.showMessageDialog(null,e);
       
       }
       
    
    }//GEN-LAST:event_jLabel38MouseClicked

    private void tabelDataSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataSiswaMouseClicked
      try{ int i = tabelDataSiswa.getSelectedRow();
            TableModel mode = tabelDataSiswa.getModel();
             
            jTextField3.setText(mode.getValueAt(i, 0).toString());
            jTextField2.setText(mode.getValueAt(i, 1).toString());
            jTextField4.setText(mode.getValueAt(i, 2).toString());
            String gender = mode.getValueAt(i, 3).toString();
             if ( "Laki-Laki".equals(gender)){
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton2.setSelected(true);
            }
            java.util.Date tgl_mulai = date.parse((String)mode.getValueAt(i, 4));
            java.util.Date tgl_selsai = date.parse((String)mode.getValueAt(i, 5));
           
            jDateChooser1.setDate(tgl_mulai);
            jDateChooser2.setDate(tgl_selsai);
            
           String divisi = mode.getValueAt(i, 6).toString();
             if ( "PSG".equals(divisi)){
                jRadioButton3.setSelected(true);
            } else {
                jRadioButton4.setSelected(true);
            }
             jTextField3.setEditable(false);
             
        } catch(Exception e){

        }    
    }//GEN-LAST:event_tabelDataSiswaMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            int yn = JOptionPane.showConfirmDialog(null, "Keluar aplikasi ?", "Keluar", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                Login l = new Login();
                l.setVisible(true);
                this.dispose();
            } else {
                
            }
            
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
       int i = tabelDataSiswa.getSelectedRow();
        TableModel mode = tabelDataSiswa.getModel();
            
        try {
            int yn = JOptionPane.showConfirmDialog(null, "Yakin menghapus data ?", "Hapus data", JOptionPane.YES_NO_OPTION);
            if (yn == 0){
                PreparedStatement ps = c.prepareStatement("delete from datasiswa where Nis_Siswa='"+mode.getValueAt(i, 0).toString()+"'");
                ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data terhapus");
               tabelDataSiswa();
               tabelDataSekolah();
               tabelNilaiSiswa();
               tabselJadwalPsg();
               tabelAbsen();
               reset();
            } else {
                
            }
            
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        printReport("src/report/RreportSekolah.jrxml");
    }//GEN-LAST:event_jLabel44MouseClicked

    private void tabelNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNilaiMouseClicked
try{ int i = tabelNilai.getSelectedRow();
            TableModel mode = tabelNilai.getModel();
             
            jTextField7.setText(mode.getValueAt(i, 0).toString());
            jTextField8.setText(mode.getValueAt(i, 1).toString());
            jTextField9.setText(mode.getValueAt(i, 2).toString());
            jTextField12.setText(mode.getValueAt(i, 3).toString());
            jTextField11.setText(mode.getValueAt(i, 4).toString());
            
            
           String divisi = mode.getValueAt(i, 5).toString();
             if ( "PSG".equals(divisi)){
                jRadioButton5.setSelected(true);
            } else {
                jRadioButton6.setSelected(true);
            }
             System.out.println("some");
             System.out.println(mode.getValueAt(i, 6).toString());
             String s = mode.getValueAt(i, 6).toString();
             if(mode.getValueAt(i, 6).equals(null)){
                 jTextField10.setText("Belum dinilai");
             } else {
                 jTextField10.setText(s);
             }
             
             jTextField7.setEditable(false);
             jTextField8.setEditable(false);
             jTextField9.setEditable(false);
             jTextField12.setEditable(false);
             jTextField11.setEditable(false);
             
        } catch(Exception e){

        }    
    }//GEN-LAST:event_tabelNilaiMouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
       try{
           
           PreparedStatement ps = c.prepareStatement("insert into nilai values (?,?)");
           ps.setString(1, jTextField7.getText());
           ps.setString(2, jTextField10.getText());
          
          
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Nilai berhasil ditambahkan");
           tabelNilaiSiswa();
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText(""); 
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
       } catch(Exception e){
           System.out.println("Gagal tambahkan data");
           JOptionPane.showMessageDialog(null,e);
       
       }
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
       try{
           PreparedStatement ps = c.prepareStatement("UPDATE nilai SET nilai_siswa=? WHERE nis_siswa=?");
           
           ps.setString(1, jTextField10.getText());
           ps.setString(2, jTextField7.getText());
           
      
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil diubah");
           tabelNilaiSiswa();
          jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText(""); 
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
       
       } catch(Exception e){
           System.out.println("Gagal ubah data");
           JOptionPane.showMessageDialog(null,e);
       
       }
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        Object [] header = {"NIS","Nama Siswa","Tanggal Mulai","Tanggal Selesai","Divisi"
        };
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelJadwal.setModel(model);
        try{
            PreparedStatement ps = c.prepareStatement("select * from datasiswa where concat(Nis_Siswa,Nama_Siswa,Asal_Sekolah,Jenis_Kelamin,Tanggal_Masuk,Tanggal_Selesai,Divisi) like '%"+jTextField6.getText()+"%'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("Nis_Siswa");
                String c2 = rs.getString("Nama_Siswa");
                String c5 = rs.getString("Tanggal_Masuk");
                String c6 = rs.getString("Tanggal_Selesai");
                String c7 = rs.getString("Divisi");
                
                String[] data = {c1,c2,c5,c6,c7};
                model.addRow(data);
            }
        } catch( Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
     
        String nis_siswa = jTextField7.getText();
        System.out.println(jTextField10.getText());
        if(jTextField10.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Input nilai");
           
        } else {
            try {
         
            param.put("parameter1",nis_siswa);
            String rpt = "src/report/surat_siswa.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rpt);
            JasperPrint jpp = JasperFillManager.fillReport(jr, param,c);
            JasperViewer.viewReport(jpp,false);
            
            
        } catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
    }//GEN-LAST:event_jLabel53MouseClicked

    private void printWithParam(String paramData, String fileReport) {
        
            try {
            
            param.put("parameter1",paramData);
            String rpt = fileReport;
            JasperReport jr = JasperCompileManager.compileReport(rpt);
            JasperPrint jpp = JasperFillManager.fillReport(jr, param,c);
            JasperViewer.viewReport(jpp,false);
            
            
        } catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void printReport(String fileReport) {
        
            try {
            
            
            String rpt = fileReport;
            JasperReport jr = JasperCompileManager.compileReport(rpt);
            JasperPrint jpp = JasperFillManager.fillReport(jr, param,c);
            JasperViewer.viewReport(jpp,false);
            
            
        } catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        printReport("src/report/dataSiswa.jrxml");
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        String tanggal = jLabel29.getText();
       String waktu = jLabel27.getText();
       if(absenByNip(jTextField1.getText())){
            try {
            PreparedStatement ps = c.prepareStatement("insert into absen values (?,?,?)");
           ps.setString(1, jTextField1.getText());
           ps.setString(2, jLabel29.getText());
           ps.setString(3, jLabel27.getText());
           ps.executeUpdate();
           AddRowToTabelAbsen(new Object[]{
               jTextField1.getText(),
               jLabel29.getText(),
               jLabel27.getText(),
           });
       } catch(SQLException e){
           System.out.println("Gagal melakukan absen");
           JOptionPane.showMessageDialog(null,e);
       }
            
       } else {
         JOptionPane.showMessageDialog(null, "NIS Tidak ditemukan");
       }
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        printWithParam(null, "src/report/ReportAbsen.jrxml");
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        printReport("src/report/ReportNilai.jrxml");
    }//GEN-LAST:event_jLabel56MouseClicked
public void tabelAbsen(){
        Object [] header = {"NIS","Tanggal Absen","Waktu Absen"
    };
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelabsen.setModel(model);
        try{
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement("select * from absen order by tanggal asc");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("nis");
                String c2 = rs.getString("tanggal");
                String c3 = rs.getString("waktu");
                
                String[] data = {c1,c2,c3};
                model.addRow(data);
            }
        } catch( Exception e){
            
        }
    }

public void tabelDataSiswa(){
        Object [] header = {"NIS","Nama Siswa","Asal Sekolah", "Jenis Kelamin","Tanggal Mulai","Tanggal Selesai","Divisi"
    };
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelDataSiswa.setModel(model);
        try{
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement("select * from datasiswa order by Nis_Siswa asc");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("Nis_Siswa");
                String c2 = rs.getString("Nama_Siswa");
                String c3 = rs.getString("Asal_Sekolah");
                String c4 = rs.getString("Jenis_Kelamin");
                String c5 = rs.getString("Tanggal_Masuk");
                String c6 = rs.getString("Tanggal_Selesai");
                String c7 = rs.getString("Divisi");
                
                String[] data = {c1,c2,c3,c4,c5,c6,c7};
                model.addRow(data);
            }
            
        } catch( Exception e){
            
        }
    }

public void tabelNilaiSiswa(){
        Object [] header = {"NIS","Nama Siswa","Asal Sekolah","Tanggal Mulai","Tanggal Selesai","Divisi","Nilai"
    };
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelNilai.setModel(model);
        try{
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement("SELECT datasiswa.Nis_Siswa, datasiswa.Nama_Siswa, datasiswa.Asal_Sekolah, datasiswa.Tanggal_Masuk, datasiswa.Tanggal_Selesai, datasiswa.Divisi, nilai.nilai_siswa from datasiswa LEFT JOIN nilai ON datasiswa.Nis_Siswa=nilai.nis_siswa ORDER BY datasiswa.Nis_Siswa ASC;");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("Nis_Siswa");
                String c2 = rs.getString("Nama_Siswa");
                String c3 = rs.getString("Asal_Sekolah");
                String c5 = rs.getString("Tanggal_Masuk");
                String c6 = rs.getString("Tanggal_Selesai");
                String c7 = rs.getString("Divisi");
                String c8 = rs.getString("nilai_siswa");
                
                String[] data = {c1,c2,c3,c5,c6,c7,c8};
                model.addRow(data);
            }
            jTextField7.setEditable(false);
             jTextField8.setEditable(false);
             jTextField9.setEditable(false);
             jTextField12.setEditable(false);
             jTextField11.setEditable(false);
        } catch( Exception e){
            
        }
    }

public void tabselJadwalPsg(){
    Object [] header = {"NIS","Nama Siswa","Tanggal Mulai","Tanggal Selesai","Divisi"
    };
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelJadwal.setModel(model);
        try{
            
            PreparedStatement ps = c.prepareStatement("select * from datasiswa order by Nis_Siswa asc");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("Nis_Siswa");
                String c2 = rs.getString("Nama_Siswa");
                String c5 = rs.getString("Tanggal_Masuk");
                String c6 = rs.getString("Tanggal_Selesai");
                String c7 = rs.getString("Divisi");
                
                String[] data = {c1,c2,c5,c6,c7};
                model.addRow(data);
            }
            
        } catch( Exception e){
            
        }
}

public void tabelDataSekolah(){
        Object [] header = {"NIS","Nama Siswa","Asal Sekolah", "Jenis Kelamin","Tanggal Mulai","Tanggal Selesai"
    };
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        tabelDataSekolah.setModel(model);
        try{
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement("select * from datasiswa order by Nis_Siswa asc");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String c1 = rs.getString("Nis_Siswa");
                String c2 = rs.getString("Nama_Siswa");
                String c3 = rs.getString("Asal_Sekolah");
                String c4 = rs.getString("Jenis_Kelamin");
                String c5 = rs.getString("Tanggal_Masuk");
                String c6 = rs.getString("Tanggal_Selesai");
                
                String[] data = {c1,c2,c3,c4,c5,c6};
                model.addRow(data);
            }
            
        } catch( Exception e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absen;
    private javax.swing.JPanel center;
    private javax.swing.JPanel dataSekolah;
    private javax.swing.JPanel dataSiswa;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jadwaPsg;
    private javax.swing.JPanel nilaiSiswa;
    private static javax.swing.JTable tabelDataSekolah;
    public static javax.swing.JTable tabelDataSiswa;
    private static javax.swing.JTable tabelJadwal;
    private static javax.swing.JTable tabelNilai;
    private static javax.swing.JTable tabelabsen;
    // End of variables declaration//GEN-END:variables
}
